name = "subtitle-flow-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
GEMINI_API_KEY = ""

[env.production]
name = "subtitle-flow-worker-prod"

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true

[placement]
region = "aws:ap-northeast-1"